In [23]:
import numpy as np
A = np.eye(8,8)
print(A)


[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [33]:
np.eye(8, dtype=int)[:, ::-1]

array([[0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
B = np.zeros((8, 8), dtype=int)

for i in range(8):
    for j in range(8):
        B[i, j] = 1 if i + j == 8 - 1 else 0
print(B)

[[0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [25]:
det_A = np.linalg.det(A)
print(det_A)
det_B = np.linalg.det(B)
print(det_B)

1.0
1.0


In [26]:
print(np.dot(A,B))


[[0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]]


In [27]:
print(A+B)


[[1. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 1.]]


In [28]:
print(A-B)


[[ 1.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  1.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  1.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  1. -1.  0.  0.  0.]
 [ 0.  0.  0. -1.  1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  1.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.  1.  0.]
 [-1.  0.  0.  0.  0.  0.  0.  1.]]


In [29]:
print(np.divide(2*A,B))


[[inf nan nan nan nan nan nan  0.]
 [nan inf nan nan nan nan  0. nan]
 [nan nan inf nan nan  0. nan nan]
 [nan nan nan inf  0. nan nan nan]
 [nan nan nan  0. inf nan nan nan]
 [nan nan  0. nan nan inf nan nan]
 [nan  0. nan nan nan nan inf nan]
 [ 0. nan nan nan nan nan nan inf]]


C:\Users\kytra\AppData\Local\Temp\ipykernel_9440\3572865382.py:1: RuntimeWarning: divide by zero encountered in divide
  print(np.divide(2*A,B))
C:\Users\kytra\AppData\Local\Temp\ipykernel_9440\3572865382.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.divide(2*A,B))
