# Bài 1:                                                                                       

In [5]:
import numpy as np

A = np.zeros((3,4))
B = np.ones((2,4))
C = np.full((4,4),5)
D = np.eye(5)
E = np.random.random((4,6))
print(A)
print(B)
print(C)
print(D)
print(E)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0.42785365 0.60761552 0.88896131 0.53270452 0.62112483 0.25911058]
 [0.63693585 0.06125048 0.2960267  0.05922125 0.29277282 0.48201933]
 [0.9339914  0.40780973 0.13381689 0.38914915 0.91156949 0.29728291]
 [0.39079005 0.60156929 0.37343675 0.70384635 0.33474788 0.08970587]]


In [6]:
A = np.eye(5)
B = np.zeros((5,5))
for i in range(5):
    for j in range(5):
        if i == j:
            A[i,j] = 1
        else:
            A[i,j] = 0
        B[i,j] = 2*i + j
print(A)
print(B)
print(np.linalg.det(A))
print(np.linalg.det(B))
print(A*B)
print(A+B)
print(A-B)
print(4*A/B)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[ 0.  1.  2.  3.  4.]
 [ 2.  3.  4.  5.  6.]
 [ 4.  5.  6.  7.  8.]
 [ 6.  7.  8.  9. 10.]
 [ 8.  9. 10. 11. 12.]]
1.0
0.0
[[ 0.  0.  0.  0.  0.]
 [ 0.  3.  0.  0.  0.]
 [ 0.  0.  6.  0.  0.]
 [ 0.  0.  0.  9.  0.]
 [ 0.  0.  0.  0. 12.]]
[[ 1.  1.  2.  3.  4.]
 [ 2.  4.  4.  5.  6.]
 [ 4.  5.  7.  7.  8.]
 [ 6.  7.  8. 10. 10.]
 [ 8.  9. 10. 11. 13.]]
[[  1.  -1.  -2.  -3.  -4.]
 [ -2.  -2.  -4.  -5.  -6.]
 [ -4.  -5.  -5.  -7.  -8.]
 [ -6.  -7.  -8.  -8. -10.]
 [ -8.  -9. -10. -11. -11.]]
[[       inf 0.         0.         0.         0.        ]
 [0.         1.33333333 0.         0.         0.        ]
 [0.         0.         0.66666667 0.         0.        ]
 [0.         0.         0.         0.44444444 0.        ]
 [0.         0.         0.         0.         0.33333333]]


C:\Users\kytra\AppData\Local\Temp\ipykernel_16624\1251618603.py:17: RuntimeWarning: divide by zero encountered in divide
  print(4*A/B)


# Bài 2 :

### Cách 1:

- Xác suất lấy được 3 trái hư:

$$\begin{align}

P(AAA) = P(A) \times P(A) \times P(A) \\
P(A) = \frac{\text{số trái hư còn lại}}{\text{số trái trong sọt}}\\
P(AAA) = \frac{4}{10} \times \frac{3}{9} \times \frac{2}{8} = \frac{1}{30}\\

\end{align}$$
- Xác suất lấy được 1 trái hư :
$$\begin{align}
P(A\overline{A}\overline{A} + \overline{A}A\overline{A} + \overline{A}\overline{A}A) = P(A) \times P(B) \times P(B) + P(B) \times P(A) \times P(B) + P(B) \times P(B) \times P(A)\\
P(A\overline{A}\overline{A} + \overline{A}A\overline{A} + \overline{A}\overline{A}A) = 3 \times \left(\frac{4}{10} \times \frac{6}{9} \times \frac{5}{8}\right) = \frac{1}{2}\\
\end{align}$$
- Xác suất lấy được ít nhất một trái hư:
$$P(\text{ính nhất một trái hư}) = 1 - P(\text{không có trái hư})\\
P(\text{không có trái hư}) = P(BBB) = P(B) \times P(B) \times P(B)\\
P(\text{ính nhất một trái hư}) = 1 - P(BBB) = 1 - \frac{6}{10} \times \frac{5}{9} \times \frac{4}{8} = \frac{5}{6}\\$$
- Xác suất lấy được nhiều nhất 2 trái hư:
$$
P(\leq 2 \text{ trái hư}) = P(\text{không có trái hư}) + P(1 \text{ trái hư}) + P(2 \text{ trái hư})\\
P(\leq 2 \text{ trái hư}) = P(BBB) + P(A\overline{A}\overline{A} + \overline{A}A\overline{A}) = \frac{6}{10} \times \frac{5}{9} \times \frac{4}{8} + \frac{90}{240} = \frac{2}{3}\\
$$

### Cách 2:

In [7]:
from sympy import nsimplify

# Số trái cam và trái hư
total_oranges = 10
defective_oranges = 4

# Xác suất lấy được 3 trái hư
prob_3_defective = nsimplify(defective_oranges/total_oranges * (defective_oranges-1)/(total_oranges-1) * (defective_oranges-2)/(total_oranges-2))

# Xác suất lấy được 1 trái hư
prob_1_defective = nsimplify(3 * (defective_oranges/total_oranges * (total_oranges-defective_oranges)/(total_oranges-1) * (total_oranges-defective_oranges-1)/(total_oranges-2)))

# Xác suất lấy được ít nhất một trái hư
prob_at_least_one_defective = nsimplify(1 - (total_oranges-defective_oranges)/(total_oranges) * (total_oranges-defective_oranges-1)/(total_oranges-1) * (total_oranges-defective_oranges-2)/(total_oranges-2))

# Xác suất lấy được nhiều nhất 2 trái hư
prob_at_most_2_defective = nsimplify((total_oranges-defective_oranges)/(total_oranges) * (total_oranges-defective_oranges-1)/(total_oranges-1) * (total_oranges-defective_oranges-2)/(total_oranges-2) + 3 * (defective_oranges/total_oranges * (total_oranges-defective_oranges)/(total_oranges-1) * (total_oranges-defective_oranges-1)/(total_oranges-2)))

# In kết quả
print(f"a) P(3 trái hư) = {prob_3_defective}")
print(f"b) P(1 trái hư) = {prob_1_defective}")
print(f"c) P(ính nhất một trái hư) = {prob_at_least_one_defective}")
print(f"d) P(nhiều nhất 2 trái hư) = {prob_at_most_2_defective}")


a) P(3 trái hư) = 1/30
b) P(1 trái hư) = 1/2
c) P(ính nhất một trái hư) = 5/6
d) P(nhiều nhất 2 trái hư) = 2/3


# Bài 3:

- Không có con trai:
$$ P(\text{Không có con trai}) = \binom{10}{0} \times 0.5^0 \times 0.5^{10} $$

- Có 5 con trai và 5 con gái:
$$ P(\text{5 con trai và 5 con gái}) = \binom{10}{5} \times 0.5^5 \times 0.5^5 $$

- Số con trai từ 5-7:
$$ P(5 \leq \text{Số trai} \leq 7) = P(\text{5 con trai}) + P(\text{6 con trai}) + P(\text{7 con trai}) $$
$$ = \binom{10}{5} \times 0.5^5 \times 0.5^5 + \binom{10}{6} \times 0.5^6 \times 0.5^4 + \binom{10}{7} \times 0.5^7 \times 0.5^3 $$



In [8]:
from scipy.stats import binom

# Số lượng con
n = 10

# Xác suất sinh con trai (và con gái)
p = 0.5

# a) Không có con trai
prob_no_son = binom.pmf(0, n, p)

# b) Có 5 con trai và 5 con gái
prob_5_sons_5_daughters = binom.pmf(5, n, p)

# c) Số trai từ 5 đến 7
prob_5_to_7_sons = sum(binom.pmf(k, n, p) for k in range(5, 8))

# In kết quả
print(f"a) P(Không có con trai) = {prob_no_son}")
print(f"b) P(5 con trai và 5 con gái) = {prob_5_sons_5_daughters}")
print(f"c) P(5 đến 7 con trai) = {prob_5_to_7_sons}")


a) P(Không có con trai) = 0.000976562499999999
b) P(5 con trai và 5 con gái) = 0.24609375
c) P(5 đến 7 con trai) = 0.5683593749999999


# Bài 4:

In [9]:
import numpy as np
from scipy.stats import binom
from scipy.integrate import quad

# Hàm lập bảng phân phối xác suất
def probability_distribution():
    outcomes = np.array([0, 1, 2, 3])
    probabilities = binom.pmf(outcomes, 3, 0.3)
    return outcomes, probabilities

# Hàm tính kỳ vọng
def calculate_expectation(data):
    return np.mean(data)

# Hàm tính phương sai
def calculate_variance(data):
    return np.var(data)

# Hàm tính độ lệch chuẩn
def calculate_standard_deviation(data):
    return np.std(data)

# Hàm hàm mật độ xác suất cho biến ngẫu nhiên liên tục
def f(x):
    if 0 <= x <= 30:
        return k * (30 - x)
    else:
        return 0

# Hàm tính kỳ vọng cho biến ngẫu nhiên liên tục
def continuous_expectation():
    return quad(lambda x: x * f(x), 0, 30)[0]

# Hàm tính phương sai cho biến ngẫu nhiên liên tục
def continuous_variance():
    return quad(lambda x: (x - continuous_expectation()) ** 2 * f(x), 0, 30)[0]

# Hàm tính độ lệch chuẩn cho biến ngẫu nhiên liên tục
def continuous_standard_deviation():
    return np.sqrt(continuous_variance())

# a. Lập bảng phân phối xác suất và ghi vào file data.txt
outcomes, probabilities = probability_distribution()
np.savetxt('data.txt', np.column_stack((outcomes, probabilities)), fmt='%d %.5f')

# Đọc dữ liệu từ file data.txt
data = np.loadtxt('data.txt')

# a. Áp dụng các hàm cho dữ liệu ở câu a
expectation_a = calculate_expectation(data[:, 0])
variance_a = calculate_variance(data[:, 0])
std_deviation_a = calculate_standard_deviation(data[:, 0])

# b. Áp dụng các hàm cho dữ liệu ở câu b
k = 1  # Thay đổi giá trị của k tùy thuộc vào hàm mật độ xác suất f(x)
expectation_b = continuous_expectation()
variance_b = continuous_variance()
std_deviation_b = continuous_standard_deviation()

# c. Áp dụng thư viện cho dữ liệu ở câu c
expectation_c = np.mean(data[:, 0])
variance_c = np.var(data[:, 0])
std_deviation_c = np.std(data[:, 0])

# d. (Không cung cấp thông tin đầy đủ về biến ngẫu nhiên liên tục, không thể sử dụng thư viện trực tiếp)

# Hiển thị kết quả
print("a. Kỳ vọng:", expectation_a)
print("   Phương sai:", variance_a)
print("   Độ lệch chuẩn:", std_deviation_a)

print("\nb. Kỳ vọng:", expectation_b)
print("   Phương sai:", variance_b)
print("   Độ lệch chuẩn:", std_deviation_b)

print("\nc. Kỳ vọng:", expectation_c)
print("   Phương sai:", variance_c)
print("   Độ lệch chuẩn:", std_deviation_c)
from scipy.stats import norm

# Hàm mật độ xác suất cho biến ngẫu nhiên liên tục
def f(x):
    return norm.pdf(x, loc=15, scale=5)  # Ví dụ với giả định hàm mật độ xác suất là phân phối Gaussian

# Hàm tính kỳ vọng cho biến ngẫu nhiên liên tục
expectation_d = quad(lambda x: x * f(x), 0, 30)[0]

# Hàm tính phương sai cho biến ngẫu nhiên liên tục
variance_d = quad(lambda x: (x - expectation_d) ** 2 * f(x), 0, 30)[0]

# Hàm tính độ lệch chuẩn cho biến ngẫu nhiên liên tục
std_deviation_d = np.sqrt(variance_d)

# Hiển thị kết quả
print("\nd. Kỳ vọng:", expectation_d)
print("   Phương sai:", variance_d)
print("   Độ lệch chuẩn:", std_deviation_d)


a. Kỳ vọng: 1.5
   Phương sai: 1.25
   Độ lệch chuẩn: 1.118033988749895

b. Kỳ vọng: 4500.0
   Phương sai: 9072067500.000002
   Độ lệch chuẩn: 95247.4015393596

c. Kỳ vọng: 1.5
   Phương sai: 1.25
   Độ lệch chuẩn: 1.118033988749895

d. Kỳ vọng: 14.959503059051098
   Phương sai: 24.26936341118246
   Độ lệch chuẩn: 4.926394565113767


# Câu 5:

**Ước lượng khoảng tin cậy 95% về sự khác biệt trong tỷ lệ xem tivi tại phòng ăn của người Mỹ trong độ tuổi 45-69 và 60 trở lên**

Giả sử:

* $p_1$: tỷ lệ người Mỹ trong độ tuổi 45-69 xem tivi tại phòng ăn
* $p_2$: tỷ lệ người Mỹ trong độ tuổi 60 trở lên xem tivi tại phòng ăn

Giả định hai mẫu là độc lập và có kích thước đủ lớn để sử dụng ước lượng khoảng tin cậy bằng phân phối chuẩn.

Công thức ước lượng khoảng tin cậy cho sự khác biệt giữa hai tỷ lệ là:

\begin{align*}
\text{Độ rộng của khoảng tin cậy} &= Z \sqrt{\frac{p_1(1-p_1)}{n_1} + \frac{p_2(1-p_2)}{n_2}} \\
&= 1.96 \sqrt{\frac{p_1(1-p_1)}{n_1} + \frac{p_2(1-p_2)}{n_2}}
\end{align*}

Ở đây, $Z$ là z-score tương ứng với mức tin cậy 95% (đối với một phân phối chuẩn, $Z = 1.96$), $p_1$ và $p_2$ là tỷ lệ ở hai nhóm, $n_1$ và $n_2$ là kích thước mẫu ở hai nhóm.

Giả sử $p_1 = 0.1$ (10%) cho nhóm 45-69 và $p_2 = 0.1$ (10%) cho nhóm 60 trở lên, và kích thước mẫu $n_1 = n_2 = 100$.

Thực hiện tính toán:

\begin{align*}
\text{Độ rộng của khoảng tin cậy} &= 1.96 \sqrt{\frac{0.1(1-0.1)}{100} + \frac{0.1(1-0.1)}{100}} \\
&\approx 1.96 \sqrt{\frac{0.09}{100} + \frac{0.09}{100}} \\
&\approx 1.96 \sqrt{0.0009 + 0.0009} \\
&\approx 1.96 \sqrt{0.0018} \\
&\approx 1.96 \times 0.0424 \\
&\approx 0.083
\end{align*}

Sau đó, ước lượng khoảng tin cậy cho sự khác biệt giữa hai tỷ lệ sẽ là:

\begin{align*}
\text{Khoảng tin cậy} &= (p_1 - p_2) \pm \text{Độ rộng của khoảng tin cậy} \\
&= (0.1 - 0.1) \pm 0.083 \\
&= (-0.083, 0.083)
\end{align*}

**Kết luận**

Vậy, ước lượng khoảng tin cậy 95% cho sự khác biệt trong tỷ lệ xem tivi tại phòng ăn của người Mỹ trong độ tuổi 45-69 và 60 trở lên là từ -0.083 đến 0.083.

In [10]:
import math
# Tỉ lệ cho nhóm 1 (45-69) và nhóm 2 (60 trở lên)
p1 = 0.10
p2 = 0.10
# Kích thước mẫu cho cả hai nhóm
n1 = 100
n2 = 100
# Z-score cho mức tin cậy 95%
z_score = 1.96
# Tính Margin of Error
margin_of_error = z_score * math.sqrt((p1 * (1 - p1) / n1) + (p2 * (1 - p2) / n2))
# Ước lượng khoảng tin cậy cho sự khác biệt giữa tỷ lệ hai nhóm
confidence_interval_lower = (p1 - p2) - margin_of_error
confidence_interval_upper = (p1 - p2) + margin_of_error
# In kết quả
print(f"Margin of Error: {margin_of_error:.3f}")
print(f"Confidence Interval: ({confidence_interval_lower:.3f}, {confidence_interval_upper:.3f})")


Margin of Error: 0.083
Confidence Interval: (-0.083, 0.083)


**Ước lượng khoảng tin cậy 95% cho sự khác biệt giữa các tỷ lệ xem tivi tại phòng khách, phòng sinh hoạt chung hoặc phòng làm việc của người Mỹ trong nhóm tuổi từ 25 đến 59 và nhóm từ 60 trở lên**

Giả sử:

* $p_{25-59}$: tỷ lệ người Mỹ trong nhóm tuổi từ 25 đến 59 xem tivi tại phòng khách, phòng sinh hoạt chung hoặc phòng làm việc.
* $p_{60+}$: tỷ lệ người Mỹ trong nhóm tuổi từ 60 trở lên xem tivi tại phòng khách, phòng sinh hoạt chung hoặc phòng làm việc.

Dựa trên dữ liệu đã cho, chúng ta có:

* $p_{25-59} = \frac{95\% + 95\%}{2} = 95\%$
* $p_{60+} = 93\%$
* $n_{25-59} = n_{60+} = 2000$

Do đó, độ rộng của khoảng tin cậy là:

\begin{align*}
\text{Độ rộng của khoảng tin cậy} &= Z \times \sqrt{\frac{{p_{25-59}(1-p_{25-59})}}{{n_{25-59}}} + \frac{{p_{60+}(1-p_{60+})}}{{n_{60+}}}} \\
&= 1.96 \times \sqrt{\frac{{0.95(1-0.95)}}{{2000}} + \frac{{0.93(1-0.93)}}{{2000}}} \\
&\approx 0.01470
\end{align*}

Vậy, ước lượng khoảng tin cậy 95% cho sự khác biệt giữa các tỷ lệ xem tivi tại phòng khách, phòng sinh hoạt chung hoặc phòng làm việc của người Mỹ trong nhóm tuổi từ 25 đến 59 và nhóm từ 60 trở lên là:

\begin{align*}
\text{Khoảng tin cậy} &= (p_{25-59} - p_{60+}) \pm \text{Độ rộng của khoảng tin cậy} \\
&= (0.95 - 0.93) \pm 0.01470 \\
&= (0.005, 0.035)
\end{align*}

**Kết luận**

Vậy, ước lượng khoảng tin cậy 95% cho sự khác biệt giữa các tỷ lệ xem tivi tại phòng khách, phòng sinh hoạt chung hoặc phòng làm việc của người Mỹ trong nhóm tuổi từ 25 đến 59 và nhóm từ 60 trở lên là từ 0,02 đến 0,18.


In [11]:
import math
# Tỉ lệ cho từng nhóm và kích thước mẫu
p_25_44 = 0.95
p_45_69 = 0.95
p_60_plus = 0.93
n_25_44 = 2000
n_45_69 = 2000
n_60_plus = 2000
# Tính tỷ lệ cho nhóm 25-59
p_25_59 = (p_25_44 + p_45_69) / 2
# Z-score cho mức tin cậy 95%
z_score = 1.96
# Tính Margin of Error
margin_of_error = z_score * math.sqrt((p_25_59 * (1 - p_25_59) / n_25_44) + (p_60_plus * (1 - p_60_plus) / n_60_plus))
# Ước lượng khoảng tin cậy cho sự khác biệt giữa tỷ lệ hai nhóm
confidence_interval_lower = (p_25_59 - p_60_plus) - margin_of_error
confidence_interval_upper = (p_25_59 - p_60_plus) + margin_of_error
# In kết quả
print(f"Tỉ lệ 25-59: {p_25_59:.3f}")
print(f"Margin of Error: {margin_of_error:.3f}")
print(f"Confidence Interval: ({confidence_interval_lower:.3f}, {confidence_interval_upper:.3f})")


Tỉ lệ 25-59: 0.950
Margin of Error: 0.015
Confidence Interval: (0.005, 0.035)


# Bài 6:

Để xác định kích thước mẫu cần thiết cho cuộc điều tra mới, chúng ta có thể sử dụng công thức sau:

```
n = (Z^2 * p * (1 - p)) / E^2
```

Trong đó:

* n là kích thước mẫu cần thiết
* Z là giá trị z-score tương ứng với xác suất mong muốn (đối với 90%, Z ≈ 1.645)
* p là Ước lượng tỷ lệ từ cuộc điều tra ban đầu (không có giá trị cụ thể trong trường hợp này, chúng ta có thể sử dụng 0.5, giả định một phân phối đồng đều)
* E là biên sai số mong muốn

Từ dữ liệu được cung cấp, chúng ta có:

* Z ≈ 1.645
* E = 0.04

Thay thế các giá trị này vào công thức, chúng ta có:

```
n = (1.645^2 * 0.5 * (1 - 0.5)) / 0.04^2
```

```
n = (2.651 * 0.25) / 0.0016
```

```
n = 422.5625
```

Vì vậy, kích thước mẫu cần thiết là **xấp xỉ 166 nhà bán buôn**.

Cần lưu ý rằng đây chỉ là một ước tính, và kích thước mẫu thực tế cần thiết có thể thay đổi tùy thuộc vào các yếu tố khác, chẳng hạn như tính đồng nhất của quần thể.

In [12]:
import math
def calculate_sample_size(z_score, p, margin_of_error):
   """Tính kích thước mẫu cần thiết cho một cuộc điều tra.
   Args:
       z_score (float): Giá trị z-score tương ứng với xác suất mong muốn.
       p (float): Ước lượng tỷ lệ từ cuộc điều tra ban đầu.
       margin_of_error (float): Biên sai số mong muốn.
   Returns:
       int: Kích thước mẫu cần thiết.
   """
   n = (z_score**2 * p * (1 - p)) / (margin_of_error**2)
   return math.ceil(n)  # Làm tròn lên số nguyên gần nhất
# Dữ liệu cho bài toán
z_score = 1.645  # Xác suất 90%
p = 0.5  # Không có ước lượng tỷ lệ từ cuộc điều tra ban đầu, giả sử phân phối đồng đều
margin_of_error = 0.04
# Tính toán kích thước mẫu
sample_size = calculate_sample_size(z_score, p, margin_of_error)
# In kết quả
print("Kích thước mẫu cần thiết:", sample_size)

Kích thước mẫu cần thiết: 423


# Bài 7:

**Tính toán bằng tay**

Để ước lượng sự khác biệt về thời gian trung bình để lắp ráp chính xác trong giới hạn 1 phút với xác suất bằng với 0.95, thì biên sai số cần phải nhỏ hơn hoặc bằng 1 phút.

Sử dụng công thức tính kích thước mẫu cho một thí nghiệm so sánh hai phương pháp, chúng ta có:

```
n = (2 * z^2 * σ^2) / (ε^2)
```

Trong đó:

* n là kích thước mẫu cần thiết cho mỗi nhóm
* z là giá trị z-score cho mức độ tin cậy 95%, là 1.96
* σ là độ lệch chuẩn của quần thể, là 8 phút
* ε là biên sai số, là 1 phút

Thay các giá trị vào công thức, ta có:

```
n = (2 * 1.96^2 * 8^2) / (1^2)
```

```
n = 492
```

Vậy, cần phải đưa **492 công nhân vào mỗi nhóm huấn luyện** để đáp ứng yêu cầu của bài toán.



In [13]:
import math
import scipy.stats
def calculate_sample_size_per_group(population_std_dev, margin_of_error, confidence_level=0.95):
  """Tính kích thước mẫu cần thiết cho mỗi nhóm trong một thí nghiệm so sánh hai phương pháp.

  Args:
    population_std_dev (float): Độ lệch chuẩn của quần thể.
    margin_of_error (float): Biên sai số mong muốn.
    confidence_level (float, optional): Mức độ tin cậy. Defaults to 0.95.

  Returns:
    int: Kích thước mẫu cần thiết cho mỗi nhóm.
  """
  z_score = scipy.stats.norm.ppf(1 - (1 - confidence_level) / 2)  # Tính z-score từ mức độ tin cậy
  n = (2 * z_score**2 * population_std_dev**2) / (margin_of_error**2)
  return math.ceil(n)  # Làm tròn lên số nguyên gần nhất
# Dữ liệu cho bài toán
population_std_dev = 8  # Độ lệch chuẩn của quần thể
margin_of_error = 1  # Biên sai số mong muốn
# Tính toán kích thước mẫu cần thiết cho mỗi nhóm
sample_size_per_group = calculate_sample_size_per_group(population_std_dev, margin_of_error)
# In kết quả
print("Kích thước mẫu cần thiết cho mỗi nhóm:", sample_size_per_group)


Kích thước mẫu cần thiết cho mỗi nhóm: 492
